export default [
    {
        id:1,
        nome:"Maria Josefina",
        sexo: "F",
        idade: 20,
        renda:5000.00,
      },
      {
        id:2,
        nome:"Carla Souza",
        sexo: "F",
        idade: 16,
        renda:10800.00,
      },
      {
        id:3,
        nome:"Chiquito Bacana",
        sexo: "M",
        idade: 14,
        renda:1800.00,
      },
     {
       id:4,
       nome:"Rosana Amaral",
       sexo: "F",
       idade: 40,
       renda:2600.00,
     },
     {
       id:5,
       nome:"Chico Souza",
       sexo: "M",
       idade: 48,
       renda:18000.00,
     },
     {
       id:6,
       nome:"Carlos Fergosa",
       sexo: "M",
       idade:  24,
       renda:3200.00,
     },
     {
       id:7,
       nome:"Walter Vaqueiro",
       sexo: "M",
       idade:  16,
       renda:6000.00,
     },
     {
       id:8,
       nome:"Miguel Matos",
       sexo: "M",
       idade: 64,
       renda:3600.00,
     },
     {
       id:9,
       nome:"Sophia Souza",
       sexo: "F",
       idade:  18,
       renda:12800.00,
     },
     {
       id:10,
       nome:"Célio Abdias",
       sexo: "M",
       idade:  17,
       renda:4500.00,
     },
     {
       id:11,
       nome:"Bruna Santos",
       sexo: "F",
       idade: 25,
       renda:8800.00,
     },
     {
       id:12,
       nome:"André Gois",
       sexo: "M",
       idade: 48,
       renda:7500.00,
     },
     {
       id:13,
       nome:"Beatriz Silva",
       sexo: "F",
       idade: 32,
       renda:8700.00,
     },
     {
       id:14,
       nome:"Paula Ferreira",
       sexo: "F",
       idade: 28,
       renda:9100.00,
     },
     {
       id:15,
       nome:"Carla Souza",
       sexo: "F",
       idade: 26,
       renda:10800.00,
     },
     {
       id:16,
       nome:"Jorginho da Silva",
       sexo: "M",
       idade:  10,
       renda:8250.00,
     },
     {
       id:17,
       nome:"Flávio Gomes",
       sexo: "M",
       idade: 15,
       renda:12800.00,
     },
     {
       id:18,
       nome:"Everton Ribeiro",
       sexo: "M",
       idade: 26,
       renda:5600.00,
     },
     {
       id:19,
       nome:"Alex dos Santos",
       sexo: "M",
       idade: 32,
       renda: 14000.00,
     },
     {
       id:20,
       nome:"João Calazans",
       sexo: "M",
       idade: 38,
       renda:9600.00,
     },
     {
       id:21,
       nome:"Eduardo Fernandes",
       sexo: "M",
       idade: 54,
       renda:7500.00,
     },
     {
       id:22,
       nome:"Márcio Filho",
       sexo: "M",
       idade: 83,
       renda:6420.00,
     },
     {
       id:23,
       nome:"Marcelo Santos",
       sexo: "M",
       idade: 32,
       renda:5310.00,
     },
     {
       id:24,
       nome:"Ivan Santos",
       sexo: "M",
       idade: 72,
       renda:4300.00,
     },
     {
       id:25,
       nome:"Zumira dos Santos",
       sexo: "F",
       idade: 64,
       renda:8800.00,
     },
     {
       id:26,
       nome:"Lucas Santos",
       sexo: "M",
       idade: 56,
       renda:10000.00,
     },
     {
       id:27,
       nome:"Carlos Alberto Oliveira",
       sexo: "M",
       idade: 65,
       renda:7900.00,
     },
     {
       id:28,
       nome:"Isabela Santana",
       sexo: "F",
       idade: 32,
       renda:7500.00,
     },
     {
       id:29,
       nome:"Cauê Alves",
       sexo: "M",
       idade: 23,
       renda:7500.00,
     },
     {
       id:30,
       nome:"Ricard Carvalho",
       sexo: "M",
       idade: 16,
       renda:15800.00,
     },
     {
       id:31,
       nome:"Pedro Santos",
       sexo: "M",
       idade: 12,
       renda:9800.00,
     },
     {
       id:32,
       nome:"Márcio Herobrine",
       sexo: "M",
       idade: 18,
       renda:3100.00,
     }
 
 ]

 